### ISSUE TITLE
pdf conversion without writing to disk

### ISSUE THREAD

**Issue by zdenop** [Altabeh/tesseract-ocr-wrapper#1]
https://github.com/Altabeh/tesseract-ocr-wrapper/blob/826068ff01ab8914eda355d595f68825b68a8c0a/utils.py#L83-L92

Did you  consider to convert pdf to image without writing to disk? With pymupdf (fitz) it is possible.

Example code e.g. https://bucket401.blogspot.com/2021/03/pdf-to-imagemultipage-in-python.html

**Comment by Altabeh** [comment]
I think I didn't use fitz because I wasn't convinced that it would be any RAM-friendlier than using ghostscript. The point of using `TemporaryDirectory()` here is really to make sure that every time a PDF is picked out of a bunch and is converted to a set of images, then stuff won't get dumped into the memory or disk and remain there throughout many iterations over other PDF files.

**Comment by Altabeh** [comment]
If you think `fitz.open()` is a better choice as far as I/O is concerned, I'll take a look.

**Comment by zdenop** [comment]
@robinwatts: do you have any suggestion? You mentioned that you tried to integrate tesseract to [MuPDF](https://github.com/tesseract-ocr/tesseract/pull/3065#issuecomment-660065748).

**Comment by robinwatts** [comment]
MuPDF has a tesseract integration, yes. Apologies for the delay in responding, I never check my github notifications, it seems.

IME, tesseract copes better with antialiased input than hard-edged black/white text. MuPDF is better positioned to create such documents than Ghostscript is. Being experienced with both the Ghostscript and MuPDF APIs, I feel that MuPDF's API is probably closer to what you'd like. Feel free to drop me an email to discuss this (or pop into our Discord channel).
